# Glossary of Mathematical Symbols {#symbol-glossary}

+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| Symbol                            | Definition                                                                                                                                                                                                                                                                                                                              |                                                         |
+===================================+=========================================================================================================================================================================================================================================================================================================================================+=========================================================+
| $\mathbf{\Omega}$                 | A $p\times p$ population covariance (correlation) matrix without model error.                                                                                                                                                                                                                                                           |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\gamma}$             | A vector of $h$ free model parameters.                                                                                                                                                                                                                                                                                                  |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\hat{\boldsymbol{\gamma}}$       | An estimated vector of free parameters.                                                                                                                                                                                                                                                                                                 |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\gamma}_0$           | A particular vector of free parameters such that $\boldsymbol{\Omega} = \boldsymbol{\Omega}(\boldsymbol{\gamma}_0)$ .                                                                                                                                                                                                                   |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{E}$                      | A symmetric $p \times p$ matrix representing the effects of model error.                                                                                                                                                                                                                                                                |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Sigma}$             | A $p \times p$ population covariance (correlation) matrix with model error such that $\boldsymbol{\Sigma} = \boldsymbol{\Omega} + \mathbf{E}$.                                                                                                                                                                                          |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{S}$                      | A $p \times p$ sample covariance (correlation) matrix.                                                                                                                                                                                                                                                                                |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\hat{F}$                         | A minimum objective function value for a hypothesized model $\\hat{F} = F(\\mathbf{S}, \\boldsymbol{\\Omega}(\\hat{\\boldsymbol{\\gamma}}))$ obtained by minimizing a discrepancy function.                                                                                                                                           |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $N$                               | Sample size for $\mathbf{S}$.                                                                                                                                                                                                                                                                                                           |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Lambda}$            | A $p \times k$ factor pattern matrix.                                                                                                                                                                                                                                                                                                 |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Phi}$               | A $k \times k$ major factor correlation matrix.                                                                                                                                                                                                                                                                                       |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Psi}$               | A $p \times p$ diagonal matrix containing the uniqueness variances.                                                                                                                                                                                                                                                                   |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{W}$                      | A $p \times q$ matrix of minor factor loadings for $q$ minor common factors in the Tucker, Koopman, and Linn (TKL; 1969) method.                                                                                                                                                                                                      |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{W}^*$                    | A $p \times q$ provisional matrix that is scaled to create $\mathbf{W}$.                                                                                                                                                                                                                                                              |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\nu_\textrm{e} \in [0,1]$        | A parameter used in the TKL method that controls the proportion of uniqueness variances that is reapportioned to the minor common factors.                                                                                                                                                                                              |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\epsilon \in [0,1]$              | A parameter used in the TKL method that controls how minor common factor variance is distributed among the minor common factors.                                                                                                                                                                                                        |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathcal{N}(\mu, \sigma^2)$      | A normal distribution with a mean ($\mu$) and variance ($\sigma^2$).                                                                                                                                                                                                                                                                    |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Psi}^*$             | A provisional matrix of uniqueness variances used to create $\mathbf{W}$.                                                                                                                                                                                                                                                               |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\textrm{dg}(\cdot)$              | An operator such that for a square matrix $\mathbf{A}$, $\textrm{dg}(\mathbf{A})$ returns a diagonal matrix containing the diagonal elements of $\mathbf{A}$.                                                                                                                                                                           |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{L}$                      | A super matrix containing major and minor factor loadings used in the extension of the TKL method proposed by Hong (1999).                                                                                                                                                                                                              |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{C}$                      | The correlation matrix for both the major and minor common factors used in the extension of the TKL method proposed by Hong (1999).                                                                                                                                                                                                     |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Gamma}$             | A $q \times q$ matrix of correlations between the minor common factors used in the extension of the TKL method proposed by Hong (1999).                                                                                                                                                                                               |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Upsilon}$           | A $k \times q$ matrix of correlations between the major and minor common factors used in the extension of the TKL method proposed by Hong (1999).                                                                                                                                                                                     |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\delta$                          | A desired discrepancy function value specified in the Cudeck and Browne model-error method (CB; 1992) such that $F(\\boldsymbol{\\Sigma}, \\boldsymbol{\\Omega}(\\boldsymbol{\\gamma})) = \\delta$.                                                                                                                                   |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\Sigma}_0$           | A $p \times p$ covariance (correlation) matrix for a particular vector of model parameters ($\boldsymbol{\gamma}_0$) such that $\\boldsymbol{\\Sigma}\_0 = \boldsymbol{\Omega}(\\boldsymbol{\\gamma}\_0) + \mathbf{E}$.                                                                                                             |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{Z}$                      | A fixed $p \times p$ matrix used in the general discrepancy function specification in \autoref{eq:disc-fun}. Different choices of $\mathbf{Z}$ make the general discrepancy function equivalent to either the ordinary least squares or maximum likelihood discrepancy functions.                                                     |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $|\cdot|$                         | The determinant operator such that for a square matrix $\mathbf{A}$, $|\mathbf{A}|$ is the determinant of $\mathbf{A}$.                                                                                                                                                                                                                 |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\boldsymbol{\gamma}_\textrm{ML}$ | The parameter vector that is the minimizer of the maximum likelihood discrepancy function.                                                                                                                                                                                                                                              |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\mathbf{B}$                      | A $\frac{1}{2}(p^2 + p) \times h$ matrix that depends on $\mathbf{Z}$ and $\dot{\boldsymbol{\Sigma}}_i = [\partial \boldsymbol{\Sigma}(\boldsymbol{\gamma})/ \partial \gamma_i]$, where $h$ is the number of free model parameters in $\boldsymbol{\gamma}$. A full definition of $\mathbf{B}$ is provided in Cudeck and Browne (1992). |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\textrm{vecs}$                   | An operator defined such that for a symmetric matrix, $\mathbf{A}$, $\textrm{vecs} \: \mathbf{A} = \begin{bmatrix} a_{11} & a_{12} & a_{22} & a_{13} & \dots & a_{pp} \end{bmatrix}^\prime$.                                                                                                                                            |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
| $\tilde{\mathbf{e}}$              | A $\\frac{1}{2}(p\^2 + p) \times 1$ provisional error vector such that $\tilde{\mathbf{e}} = \mathop{\textrm{vecs}} \tilde{\mathbf{E}}$, where $\tilde{\mathbf{E}}$ is the provisional error matrix that is scaled to create $\mathbf{E}$ in the CB method.                                                                           |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
|                                   |                                                                                                                                                                                                                                                                                                                                         |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
|                                   |                                                                                                                                                                                                                                                                                                                                         |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
|                                   |                                                                                                                                                                                                                                                                                                                                         |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
|                                   |                                                                                                                                                                                                                                                                                                                                         |                                                         |
+-----------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------+
